version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundryvtt
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /home/arastorn/Foundry/foundrydata
        target: /data
    environment:
      - FOUNDRY_ADMIN_KEY=admin
    ports:
      - target: 30000
        published: 30000
        protocol: tcp