version: "3.8"
services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundryvtt
    volumes:
        -  /home/arastorn/Foundry/foundrydata:/data
    init: true
    restart: "unless-stopped"
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
    ports:
      - 30000:30000
    secrets:
        - ./secrets.json:config.json