version: "3.8"
services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: password
      RCON_PORT: 28016
      SERVER_PORT: 25565
      TZ: "Europe/Paris"
      GUI: "FALSE"
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
      PUID: 1001
      PGID: 1001
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - /home/arastorn/minecraft/data:/data
      - /home/arastorn/minecraft/mods.txt:/extras/mods.txt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"