version: '3.8'
services:
    # gestion du home center multimédias film / séries / animées
    portainer:
        image: portainer/portainer:latest
        hostname: portainer
        container_name: portainer
        volumes:
            - /home/docker/portainer/config:/config
            - /var/run/docker.sock:/var/run/docker.sock
        # ports:
        #    - 9000:9000
        restart: unless-stopped 
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        networks:
            - default

    nginx-proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            # - '81:81'
            - '443:443'
        volumes:
            - /home/docker/nginx-proxy-manager/data:/data
            - /home/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        networks:
            - bitwarden
            - default
            - multimedias
            - foundry

    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        restart: unless-stopped
        networks:
            - management
        command: tunnel --config /home/nonroot/.cloudflared/config.yml run eyJhIjoiNDQ4YWVjMjQzMjYzNTVhMDI1ZTgxZGI4NTc4NjAyYmQiLCJ0IjoiMDQ2Zjk5NzYtZTc2Yy00NDcwLWFiYmMtMTVkN2E0MTg0OTYzIiwicyI6IlpEZ3pNekpoWVdRdE5qZGxOeTAwWkdFeUxXRTBabVV0TWpRME4yTXdNRFkyTnpVNSJ9 #Replace UUID with your actual UUID
        volumes:
            - /home/docker/cloudflared/data:/home/nonroot/.cloudflared/

networks:
    default:
        name: management
    bitwarden:
        name: bitwarden_default
        external: true
    multimedias:
        name: multimedias_default
        external: true
    foundry:
        name: foundry_default
        external: true
