version: '3.8'
services:
    # gestion du home center multimédias film / séries / animées
    portainer:
        image: portainer/portainer:latest
        hostname: portainer
        container_name: portainer
        volumes:
            - /home/docker/portainer/config:/config
            - /var/run/docker.sock:/var/run/docker.sock
        # ports:
        #    - 9000:9000
        restart: unless-stopped 
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        networks:
            - default

    nginx-proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
        #    - '81:81'
            - '443:443'
        volumes:
            - /home/docker/nginx-proxy-manager/data:/data
            - /home/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        networks:
            - bitwarden
            - default
            - multimedias
            - foundry
    
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
            - SERVERURL=wireguard.domain.com #optional
            - SERVERPORT=51820 #optional
            - PEERS=1 #optional
            - PEERDNS=auto #optional
            - INTERNAL_SUBNET=10.13.13.0 #optional
            - ALLOWEDIPS=0.0.0.0/0 #optional
            - LOG_CONFS=true #optional
        volumes:
            - /home/docker/wireguard/config:/config
            - /home/docker/wireguard/modules:/lib/modules #optional
        ports:
            - 51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        networks:
            - default

networks:
    default:
        name: management
    bitwarden:
        name: bitwarden_default
        external: true
    multimedias:
        name: multimedias_default
        external: true
    foundry:
        name: foundry_default
        external: true