version: '3.8'
services:
    # gestion du home center multimédias film / séries / animées
    portainer:
        image: portainer/portainer:latest
        hostname: portainer
        container_name: portainer
        volumes:
            - /home/docker/portainer/config:/config
            - /var/run/docker.sock:/var/run/docker.sock
        # ports:
        #    - 9000:9000
        restart: unless-stopped 
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        networks:
            - default

    nginx-proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            # - '81:81'
            - '443:443'
        volumes:
            - /home/docker/nginx-proxy-manager/data:/data
            - /home/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        networks:
            - bitwarden
            - default
            - multimedias
            - foundry

    cloudflared-tunnel:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        restart: unless-stopped
        networks:
            - default
        command: tunnel run
        environment:
            - TUNNEL_TOKEN=eyJhIjoiNDQ4YWVjMjQzMjYzNTVhMDI1ZTgxZGI4NTc4NjAyYmQiLCJ0IjoiNTc4NmY2MWQtZTAyZi00ZTY3LWFlNzktOGM1MDExMTk2MDhhIiwicyI6Ill6QXlZV1U0TmpRdFl6RmtZaTAwTW1SbUxXRTROVGt0TXpBMFpqRTNPV0U0Wm1GaiJ9
        volumes:
            - /home/docker/cloudflared/data:/home/nonroot/.cloudflared/

networks:
    default:
        name: management
    bitwarden:
        name: bitwarden_default
        external: true
    multimedias:
        name: multimedias_default
        external: true
    foundry:
        name: foundry_default
        external: true
