version: '3'
services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - /home/docker/bitwarden/data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups